import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Cinzel({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-900 text-slate-50">
    
      <body className={inter.className}>

      <Header/>
        
        {children}

        <Footer/>

      </body>
    </html>
  );
}
