import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import clsx from "clsx";

const inter = Cinzel({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-900 text-slate-50">
    
      <body className={clsx(inter.className, "relative min-h-screen")}>

      <Header/>
        
        {children}

        <Footer/>

       

        <div className="absolute pointer-events-none inset-0 -z-40 h-full 
        bg-[url('/noisetexture.jpg')] opacity-25 mix-blend-soft-light "></div>

      </body>
    </html>
  );
}
